# Generated by Django 2.2.10 on 2020-03-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('avaluos', '0001_initial'), ('avaluos', '0002_auto_20200306_1505'), ('avaluos', '0003_auto_20200306_1710'), ('avaluos', '0004_remove_mancomunado_curp'), ('avaluos', '0005_auto_20200309_1322'), ('avaluos', '0006_auto_20200311_1633'), ('avaluos', '0007_auto_20200311_1704'), ('avaluos', '0008_avaluo_localizado'), ('avaluos', '0009_auto_20200312_1527'), ('avaluos', '0010_auto_20200312_1553'), ('avaluos', '0011_auto_20200312_1610'), ('avaluos', '0012_auto_20200312_1629'), ('avaluos', '0013_auto_20200312_1630'), ('avaluos', '0014_auto_20200313_1514'), ('avaluos', '0015_auto_20200317_1447'), ('avaluos', '0016_auto_20200317_1548'), ('avaluos', '0017_alr'), ('avaluos', '0018_auto_20200317_1608'), ('avaluos', '0019_auto_20200317_1615'), ('avaluos', '0020_auto_20200317_1617'), ('avaluos', '0021_auto_20200317_1657')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('localizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('titular', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaluos.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Avaluo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('fecha_solicitud_correo', models.DateField(blank=True, null=True)),
                ('credito_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
                ('no_ext', models.CharField(blank=True, max_length=255, null=True)),
                ('no_int', models.CharField(blank=True, max_length=255, null=True)),
                ('colonia', models.CharField(blank=True, max_length=255, null=True)),
                ('lote', models.CharField(blank=True, max_length=255, null=True)),
                ('manzana', models.CharField(blank=True, max_length=255, null=True)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('localizacion_adr', models.CharField(blank=True, max_length=255, null=True)),
                ('domicilio_adr', models.CharField(blank=True, max_length=255, null=True)),
                ('alr', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Cliente')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Estado')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Municipio')),
                ('titular_adr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.ADR')),
                ('localizado', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(blank=True, choices=[('F', 'Persona Física'), ('M', 'Persona Moral')], max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=255, null=True)),
                ('curp', models.CharField(blank=True, max_length=255, null=True)),
                ('nss', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('avaluo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos_cliente', to='avaluos.Avaluo')),
            ],
        ),
        migrations.CreateModel(
            name='Mancomunado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.CharField(blank=True, max_length=255, null=True)),
                ('avaluo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mancomunado', to='avaluos.Avaluo')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaluos.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='ALR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('adr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alr', to='avaluos.ADR')),
            ],
        ),
    ]
