# Generated by Django 2.2.10 on 2020-03-05 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('abrev', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mancomunado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('rfc', models.CharField(max_length=255, null=True)),
                ('curp', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('celular', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=1)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaluos.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=1)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaluos.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='DatosCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('apellido_paterno', models.CharField(max_length=255, null=True)),
                ('apellido_materno', models.CharField(max_length=255, null=True)),
                ('rfc', models.CharField(max_length=255, null=True)),
                ('curp', models.CharField(max_length=255, null=True)),
                ('nss', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=255, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Avaluo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=255, null=True)),
                ('fecha_asignacion', models.DateField(null=True)),
                ('fecha_compromiso', models.DateField(null=True)),
                ('fecha_solicitud_correo', models.DateField(null=True)),
                ('credito_fiscal', models.CharField(max_length=255, null=True)),
                ('codigo_postal', models.CharField(max_length=255, null=True)),
                ('calle', models.CharField(max_length=255, null=True)),
                ('no_ext', models.CharField(max_length=255, null=True)),
                ('no_int', models.CharField(max_length=255, null=True)),
                ('colonia', models.CharField(max_length=255, null=True)),
                ('lote', models.CharField(max_length=255, null=True)),
                ('manzana', models.CharField(max_length=255, null=True)),
                ('localidad', models.CharField(max_length=255, null=True)),
                ('localizacion_adr', models.CharField(max_length=255, null=True)),
                ('domicilio_adr', models.CharField(max_length=255, null=True)),
                ('alr', models.CharField(max_length=255, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Cliente')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Estado')),
                ('mancomunado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Mancomunado')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Municipio')),
                ('titular_adr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.ADR')),
            ],
        ),
    ]
