# Generated by Django 2.2.10 on 2020-03-06 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluo',
            name='mancomunado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Mancomunado'),
        ),
    ]
