# Generated by Django 2.2.10 on 2020-03-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0002_auto_20200306_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscliente',
            name='persona',
            field=models.CharField(choices=[('F', 'Persona Física'), ('M', 'Persona Moral')], max_length=255, null=True),
        ),
    ]
