# Generated by Django 2.2.10 on 2020-03-20 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0002_auto_20200320_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaluo',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
