# Generated by Django 2.2.10 on 2020-03-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0003_auto_20200306_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mancomunado',
            name='curp',
        ),
    ]
