# Generated by Django 2.2.10 on 2020-03-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0003_auto_20200320_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaluo',
            old_name='folio',
            new_name='folio_institucion',
        ),
    ]
