# Generated by Django 2.2.10 on 2020-03-11 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0005_auto_20200309_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluo',
            name='datos_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.DatosCliente'),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='mancomunado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Mancomunado'),
        ),
    ]
