# Generated by Django 2.2.10 on 2020-03-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0005_auto_20200320_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Propósitos',
            },
        ),
        migrations.AlterModelOptions(
            name='bien',
            options={'verbose_name_plural': 'Tipos de Bienes'},
        ),
        migrations.AddField(
            model_name='avaluo',
            name='proposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Proposito'),
        ),
    ]
