# Generated by Django 2.2.10 on 2020-03-11 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0006_auto_20200311_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluo',
            name='datos_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.DatosCliente'),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='mancomunado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Mancomunado'),
        ),
    ]
