# Generated by Django 2.2.10 on 2020-03-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0007_auto_20200320_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Inmuebles',
            },
        ),
        migrations.AddField(
            model_name='avaluo',
            name='tipo_inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Inmueble'),
        ),
    ]
