# Generated by Django 2.2.10 on 2020-03-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0008_auto_20200320_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluo',
            name='descripcion_bien',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avaluo',
            name='domicilio_bien',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
