# Generated by Django 2.2.10 on 2020-03-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0009_auto_20200320_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaluo',
            name='descripcion_bien',
        ),
        migrations.CreateModel(
            name='DescripcionBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('avaluo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_bien', to='avaluos.Avaluo')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Bienes',
            },
        ),
    ]
