# Generated by Django 2.2.10 on 2020-03-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0009_auto_20200312_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaluo',
            name='datos_cliente',
        ),
        migrations.RemoveField(
            model_name='avaluo',
            name='mancomunado',
        ),
        migrations.AddField(
            model_name='datoscliente',
            name='avaluo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos_cliente', to='avaluos.Avaluo'),
        ),
        migrations.AddField(
            model_name='mancomunado',
            name='avaluo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mancomunado', to='avaluos.Avaluo'),
        ),
    ]
