# Generated by Django 2.2.10 on 2020-03-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0010_auto_20200324_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descripcionbien',
            options={'verbose_name_plural': 'Descripciones de Bienes'},
        ),
        migrations.AlterField(
            model_name='descripcionbien',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
