# Generated by Django 2.2.10 on 2020-03-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0010_auto_20200312_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluo',
            name='alr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='calle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='colonia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='credito_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='domicilio_adr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Estado'),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='fecha_compromiso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='fecha_solicitud_correo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='localidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='localizacion_adr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='localizado',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='lote',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='manzana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.Municipio'),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='no_ext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='no_int',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avaluo',
            name='titular_adr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaluos.ADR'),
        ),
    ]
