# Generated by Django 2.2.10 on 2020-03-31 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0012_auto_20200326_1308'),
        ('avaluos', '0011_auto_20200326_1116'),
    ]

    operations = [
    ]
