# Generated by Django 2.2.10 on 2020-03-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0012_auto_20200312_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaluo',
            name='folio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
