# Generated by Django 2.2.10 on 2020-03-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaluos', '0013_auto_20200312_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='abrev',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='is_active',
        ),
    ]
